name: Trigger RT-Thread BSP Static Build Check

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger RT-Thread BSP Static Build Check
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.RT_THREAD_PAT }}
        repository: RT-Thread/rt-thread
        event-type: online-pkgs-static-building-trigger-event
